<?php


/**
 * This class adds structure of 'auto_course_rating_data' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 07/17/09 09:48:44
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AutoCourseRatingMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AutoCourseRatingMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AutoCourseRatingPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AutoCourseRatingPeer::TABLE_NAME);
		$tMap->setPhpName('AutoCourseRating');
		$tMap->setClassname('AutoCourseRating');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('FIELD_ID', 'FieldId', 'INTEGER' , 'rating_field', 'ID', true, null);

		$tMap->addPrimaryKey('RATING', 'Rating', 'TINYINT', true, null);

		$tMap->addPrimaryKey('IMPORT_DT', 'ImportDt', 'TIMESTAMP', true, null);

		$tMap->addForeignPrimaryKey('COURSE_ID', 'CourseId', 'VARCHAR' , 'course', 'ID', true, 9);

		$tMap->addColumn('NUMBER', 'Number', 'SMALLINT', true, null);

	} // doBuild()

} // AutoCourseRatingMapBuilder
