<?php


/**
 * This class adds structure of 'course_section' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 05/13/10 22:04:47
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CourseSectionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CourseSectionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CourseSectionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CourseSectionPeer::TABLE_NAME);
		$tMap->setPhpName('CourseSection');
		$tMap->setClassname('CourseSection');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('COURSE_ID', 'CourseId', 'VARCHAR', 'course', 'ID', true, 9);

		$tMap->addColumn('SECTION_TYPE', 'SectionType', 'INTEGER', true, null);

		$tMap->addColumn('TERM', 'Term', 'TINYINT', true, null);

		$tMap->addColumn('SECTION_NUM', 'SectionNum', 'INTEGER', true, null);

		$tMap->addColumn('MEET_TIME', 'MeetTime', 'VARCHAR', true, 11);

	} // doBuild()

} // CourseSectionMapBuilder
