<?php


/**
 * This class adds structure of 'exam_comment_dig' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 12/19/09 15:53:22
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ExamCommentDigMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ExamCommentDigMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ExamCommentDigPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ExamCommentDigPeer::TABLE_NAME);
		$tMap->setPhpName('ExamCommentDig');
		$tMap->setClassname('ExamCommentDig');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('IP', 'Ip', 'VARCHAR', true, 15);

		$tMap->addForeignKey('COMMENT_ID', 'CommentId', 'INTEGER', 'exam_comment', 'ID', true, null);

		$tMap->addColumn('IS_GOOD', 'IsGood', 'BOOLEAN', true, null);

	} // doBuild()

} // ExamCommentDigMapBuilder
