<?php


/**
 * This class adds structure of 'exam' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 07/17/09 09:48:44
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ExamMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ExamMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ExamPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ExamPeer::TABLE_NAME);
		$tMap->setPhpName('Exam');
		$tMap->setClassname('Exam');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('COURSE_ID', 'CourseId', 'VARCHAR', 'course', 'ID', true, 9);

		$tMap->addForeignKey('TYPE', 'Type', 'INTEGER', 'enum_item', 'ID', true, null);

		$tMap->addColumn('YEAR', 'Year', 'SMALLINT', true, null);

		$tMap->addColumn('DESCR', 'Descr', 'VARCHAR', true, 255);

		$tMap->addColumn('FILE_PATH', 'FilePath', 'LONGVARCHAR', true, null);

	} // doBuild()

} // ExamMapBuilder
