<?php

/**
 * Base class that represents a row from the 'enum_item' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 07/19/09 20:03:12
 *
 * @package    lib.model.om
 */
abstract class BaseEnumItem extends BaseObject  implements Persistent {


  const PEER = 'EnumItemPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EnumItemPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the parent_id field.
	 * @var        int
	 */
	protected $parent_id;

	/**
	 * The value for the descr field.
	 * @var        string
	 */
	protected $descr;

	/**
	 * @var        EnumItem
	 */
	protected $aEnumItemRelatedByParentId;

	/**
	 * @var        array CourseDisciplineAssociation[] Collection to store aggregation of CourseDisciplineAssociation objects.
	 */
	protected $collCourseDisciplineAssociations;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCourseDisciplineAssociations.
	 */
	private $lastCourseDisciplineAssociationCriteria = null;

	/**
	 * @var        array EnumItem[] Collection to store aggregation of EnumItem objects.
	 */
	protected $collEnumItemsRelatedByParentId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEnumItemsRelatedByParentId.
	 */
	private $lastEnumItemRelatedByParentIdCriteria = null;

	/**
	 * @var        array Exam[] Collection to store aggregation of Exam objects.
	 */
	protected $collExams;

	/**
	 * @var        Criteria The criteria used to select the current contents of collExams.
	 */
	private $lastExamCriteria = null;

	/**
	 * @var        array ImportMapping[] Collection to store aggregation of ImportMapping objects.
	 */
	protected $collImportMappingsRelatedByImportFileType;

	/**
	 * @var        Criteria The criteria used to select the current contents of collImportMappingsRelatedByImportFileType.
	 */
	private $lastImportMappingRelatedByImportFileTypeCriteria = null;

	/**
	 * @var        array ImportMapping[] Collection to store aggregation of ImportMapping objects.
	 */
	protected $collImportMappingsRelatedByMapping;

	/**
	 * @var        Criteria The criteria used to select the current contents of collImportMappingsRelatedByMapping.
	 */
	private $lastImportMappingRelatedByMappingCriteria = null;

	/**
	 * @var        array RatingField[] Collection to store aggregation of RatingField objects.
	 */
	protected $collRatingFields;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRatingFields.
	 */
	private $lastRatingFieldCriteria = null;

	/**
	 * @var        array User[] Collection to store aggregation of User objects.
	 */
	protected $collUsers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsers.
	 */
	private $lastUserCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEnumItem object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [parent_id] column value.
	 * 
	 * @return     int
	 */
	public function getParentId()
	{
		return $this->parent_id;
	}

	/**
	 * Get the [descr] column value.
	 * 
	 * @return     string
	 */
	public function getDescr()
	{
		return $this->descr;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     EnumItem The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EnumItemPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [parent_id] column.
	 * 
	 * @param      int $v new value
	 * @return     EnumItem The current object (for fluent API support)
	 */
	public function setParentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->parent_id !== $v) {
			$this->parent_id = $v;
			$this->modifiedColumns[] = EnumItemPeer::PARENT_ID;
		}

		if ($this->aEnumItemRelatedByParentId !== null && $this->aEnumItemRelatedByParentId->getId() !== $v) {
			$this->aEnumItemRelatedByParentId = null;
		}

		return $this;
	} // setParentId()

	/**
	 * Set the value of [descr] column.
	 * 
	 * @param      string $v new value
	 * @return     EnumItem The current object (for fluent API support)
	 */
	public function setDescr($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descr !== $v) {
			$this->descr = $v;
			$this->modifiedColumns[] = EnumItemPeer::DESCR;
		}

		return $this;
	} // setDescr()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->parent_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->descr = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 3; // 3 = EnumItemPeer::NUM_COLUMNS - EnumItemPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating EnumItem object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEnumItemRelatedByParentId !== null && $this->parent_id !== $this->aEnumItemRelatedByParentId->getId()) {
			$this->aEnumItemRelatedByParentId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EnumItemPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EnumItemPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEnumItemRelatedByParentId = null;
			$this->collCourseDisciplineAssociations = null;
			$this->lastCourseDisciplineAssociationCriteria = null;

			$this->collEnumItemsRelatedByParentId = null;
			$this->lastEnumItemRelatedByParentIdCriteria = null;

			$this->collExams = null;
			$this->lastExamCriteria = null;

			$this->collImportMappingsRelatedByImportFileType = null;
			$this->lastImportMappingRelatedByImportFileTypeCriteria = null;

			$this->collImportMappingsRelatedByMapping = null;
			$this->lastImportMappingRelatedByMappingCriteria = null;

			$this->collRatingFields = null;
			$this->lastRatingFieldCriteria = null;

			$this->collUsers = null;
			$this->lastUserCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEnumItem:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EnumItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EnumItemPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEnumItem:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEnumItem:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EnumItemPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEnumItem:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EnumItemPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEnumItemRelatedByParentId !== null) {
				if ($this->aEnumItemRelatedByParentId->isModified() || $this->aEnumItemRelatedByParentId->isNew()) {
					$affectedRows += $this->aEnumItemRelatedByParentId->save($con);
				}
				$this->setEnumItemRelatedByParentId($this->aEnumItemRelatedByParentId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EnumItemPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EnumItemPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EnumItemPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCourseDisciplineAssociations !== null) {
				foreach ($this->collCourseDisciplineAssociations as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collEnumItemsRelatedByParentId !== null) {
				foreach ($this->collEnumItemsRelatedByParentId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collExams !== null) {
				foreach ($this->collExams as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collImportMappingsRelatedByImportFileType !== null) {
				foreach ($this->collImportMappingsRelatedByImportFileType as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collImportMappingsRelatedByMapping !== null) {
				foreach ($this->collImportMappingsRelatedByMapping as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRatingFields !== null) {
				foreach ($this->collRatingFields as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUsers !== null) {
				foreach ($this->collUsers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEnumItemRelatedByParentId !== null) {
				if (!$this->aEnumItemRelatedByParentId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEnumItemRelatedByParentId->getValidationFailures());
				}
			}


			if (($retval = EnumItemPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCourseDisciplineAssociations !== null) {
					foreach ($this->collCourseDisciplineAssociations as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collEnumItemsRelatedByParentId !== null) {
					foreach ($this->collEnumItemsRelatedByParentId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collExams !== null) {
					foreach ($this->collExams as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collImportMappingsRelatedByImportFileType !== null) {
					foreach ($this->collImportMappingsRelatedByImportFileType as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collImportMappingsRelatedByMapping !== null) {
					foreach ($this->collImportMappingsRelatedByMapping as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRatingFields !== null) {
					foreach ($this->collRatingFields as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUsers !== null) {
					foreach ($this->collUsers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EnumItemPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getParentId();
				break;
			case 2:
				return $this->getDescr();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EnumItemPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getParentId(),
			$keys[2] => $this->getDescr(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EnumItemPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setParentId($value);
				break;
			case 2:
				$this->setDescr($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EnumItemPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setParentId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDescr($arr[$keys[2]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);

		if ($this->isColumnModified(EnumItemPeer::ID)) $criteria->add(EnumItemPeer::ID, $this->id);
		if ($this->isColumnModified(EnumItemPeer::PARENT_ID)) $criteria->add(EnumItemPeer::PARENT_ID, $this->parent_id);
		if ($this->isColumnModified(EnumItemPeer::DESCR)) $criteria->add(EnumItemPeer::DESCR, $this->descr);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);

		$criteria->add(EnumItemPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of EnumItem (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setParentId($this->parent_id);

		$copyObj->setDescr($this->descr);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCourseDisciplineAssociations() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCourseDisciplineAssociation($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getEnumItemsRelatedByParentId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEnumItemRelatedByParentId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getExams() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addExam($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getImportMappingsRelatedByImportFileType() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addImportMappingRelatedByImportFileType($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getImportMappingsRelatedByMapping() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addImportMappingRelatedByMapping($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRatingFields() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRatingField($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUsers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUser($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     EnumItem Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EnumItemPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EnumItemPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a EnumItem object.
	 *
	 * @param      EnumItem $v
	 * @return     EnumItem The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEnumItemRelatedByParentId(EnumItem $v = null)
	{
		if ($v === null) {
			$this->setParentId(NULL);
		} else {
			$this->setParentId($v->getId());
		}

		$this->aEnumItemRelatedByParentId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the EnumItem object, it will not be re-added.
		if ($v !== null) {
			$v->addEnumItemRelatedByParentId($this);
		}

		return $this;
	}


	/**
	 * Get the associated EnumItem object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     EnumItem The associated EnumItem object.
	 * @throws     PropelException
	 */
	public function getEnumItemRelatedByParentId(PropelPDO $con = null)
	{
		if ($this->aEnumItemRelatedByParentId === null && ($this->parent_id !== null)) {
			$c = new Criteria(EnumItemPeer::DATABASE_NAME);
			$c->add(EnumItemPeer::ID, $this->parent_id);
			$this->aEnumItemRelatedByParentId = EnumItemPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEnumItemRelatedByParentId->addEnumItemsRelatedByParentId($this);
			 */
		}
		return $this->aEnumItemRelatedByParentId;
	}

	/**
	 * Clears out the collCourseDisciplineAssociations collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCourseDisciplineAssociations()
	 */
	public function clearCourseDisciplineAssociations()
	{
		$this->collCourseDisciplineAssociations = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCourseDisciplineAssociations collection (array).
	 *
	 * By default this just sets the collCourseDisciplineAssociations collection to an empty array (like clearcollCourseDisciplineAssociations());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCourseDisciplineAssociations()
	{
		$this->collCourseDisciplineAssociations = array();
	}

	/**
	 * Gets an array of CourseDisciplineAssociation objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related CourseDisciplineAssociations from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CourseDisciplineAssociation[]
	 * @throws     PropelException
	 */
	public function getCourseDisciplineAssociations($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourseDisciplineAssociations === null) {
			if ($this->isNew()) {
			   $this->collCourseDisciplineAssociations = array();
			} else {

				$criteria->add(CourseDisciplineAssociationPeer::DISCIPLINE_ID, $this->id);

				CourseDisciplineAssociationPeer::addSelectColumns($criteria);
				$this->collCourseDisciplineAssociations = CourseDisciplineAssociationPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CourseDisciplineAssociationPeer::DISCIPLINE_ID, $this->id);

				CourseDisciplineAssociationPeer::addSelectColumns($criteria);
				if (!isset($this->lastCourseDisciplineAssociationCriteria) || !$this->lastCourseDisciplineAssociationCriteria->equals($criteria)) {
					$this->collCourseDisciplineAssociations = CourseDisciplineAssociationPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCourseDisciplineAssociationCriteria = $criteria;
		return $this->collCourseDisciplineAssociations;
	}

	/**
	 * Returns the number of related CourseDisciplineAssociation objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CourseDisciplineAssociation objects.
	 * @throws     PropelException
	 */
	public function countCourseDisciplineAssociations(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCourseDisciplineAssociations === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CourseDisciplineAssociationPeer::DISCIPLINE_ID, $this->id);

				$count = CourseDisciplineAssociationPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CourseDisciplineAssociationPeer::DISCIPLINE_ID, $this->id);

				if (!isset($this->lastCourseDisciplineAssociationCriteria) || !$this->lastCourseDisciplineAssociationCriteria->equals($criteria)) {
					$count = CourseDisciplineAssociationPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCourseDisciplineAssociations);
				}
			} else {
				$count = count($this->collCourseDisciplineAssociations);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CourseDisciplineAssociation object to this object
	 * through the CourseDisciplineAssociation foreign key attribute.
	 *
	 * @param      CourseDisciplineAssociation $l CourseDisciplineAssociation
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCourseDisciplineAssociation(CourseDisciplineAssociation $l)
	{
		if ($this->collCourseDisciplineAssociations === null) {
			$this->initCourseDisciplineAssociations();
		}
		if (!in_array($l, $this->collCourseDisciplineAssociations, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCourseDisciplineAssociations, $l);
			$l->setEnumItem($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EnumItem is new, it will return
	 * an empty collection; or if this EnumItem has previously
	 * been saved, it will retrieve related CourseDisciplineAssociations from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EnumItem.
	 */
	public function getCourseDisciplineAssociationsJoinCourse($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCourseDisciplineAssociations === null) {
			if ($this->isNew()) {
				$this->collCourseDisciplineAssociations = array();
			} else {

				$criteria->add(CourseDisciplineAssociationPeer::DISCIPLINE_ID, $this->id);

				$this->collCourseDisciplineAssociations = CourseDisciplineAssociationPeer::doSelectJoinCourse($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CourseDisciplineAssociationPeer::DISCIPLINE_ID, $this->id);

			if (!isset($this->lastCourseDisciplineAssociationCriteria) || !$this->lastCourseDisciplineAssociationCriteria->equals($criteria)) {
				$this->collCourseDisciplineAssociations = CourseDisciplineAssociationPeer::doSelectJoinCourse($criteria, $con, $join_behavior);
			}
		}
		$this->lastCourseDisciplineAssociationCriteria = $criteria;

		return $this->collCourseDisciplineAssociations;
	}

	/**
	 * Clears out the collEnumItemsRelatedByParentId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEnumItemsRelatedByParentId()
	 */
	public function clearEnumItemsRelatedByParentId()
	{
		$this->collEnumItemsRelatedByParentId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEnumItemsRelatedByParentId collection (array).
	 *
	 * By default this just sets the collEnumItemsRelatedByParentId collection to an empty array (like clearcollEnumItemsRelatedByParentId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEnumItemsRelatedByParentId()
	{
		$this->collEnumItemsRelatedByParentId = array();
	}

	/**
	 * Gets an array of EnumItem objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related EnumItemsRelatedByParentId from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EnumItem[]
	 * @throws     PropelException
	 */
	public function getEnumItemsRelatedByParentId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEnumItemsRelatedByParentId === null) {
			if ($this->isNew()) {
			   $this->collEnumItemsRelatedByParentId = array();
			} else {

				$criteria->add(EnumItemPeer::PARENT_ID, $this->id);

				EnumItemPeer::addSelectColumns($criteria);
				$this->collEnumItemsRelatedByParentId = EnumItemPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EnumItemPeer::PARENT_ID, $this->id);

				EnumItemPeer::addSelectColumns($criteria);
				if (!isset($this->lastEnumItemRelatedByParentIdCriteria) || !$this->lastEnumItemRelatedByParentIdCriteria->equals($criteria)) {
					$this->collEnumItemsRelatedByParentId = EnumItemPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEnumItemRelatedByParentIdCriteria = $criteria;
		return $this->collEnumItemsRelatedByParentId;
	}

	/**
	 * Returns the number of related EnumItem objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EnumItem objects.
	 * @throws     PropelException
	 */
	public function countEnumItemsRelatedByParentId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEnumItemsRelatedByParentId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EnumItemPeer::PARENT_ID, $this->id);

				$count = EnumItemPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EnumItemPeer::PARENT_ID, $this->id);

				if (!isset($this->lastEnumItemRelatedByParentIdCriteria) || !$this->lastEnumItemRelatedByParentIdCriteria->equals($criteria)) {
					$count = EnumItemPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEnumItemsRelatedByParentId);
				}
			} else {
				$count = count($this->collEnumItemsRelatedByParentId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a EnumItem object to this object
	 * through the EnumItem foreign key attribute.
	 *
	 * @param      EnumItem $l EnumItem
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEnumItemRelatedByParentId(EnumItem $l)
	{
		if ($this->collEnumItemsRelatedByParentId === null) {
			$this->initEnumItemsRelatedByParentId();
		}
		if (!in_array($l, $this->collEnumItemsRelatedByParentId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEnumItemsRelatedByParentId, $l);
			$l->setEnumItemRelatedByParentId($this);
		}
	}

	/**
	 * Clears out the collExams collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addExams()
	 */
	public function clearExams()
	{
		$this->collExams = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collExams collection (array).
	 *
	 * By default this just sets the collExams collection to an empty array (like clearcollExams());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initExams()
	{
		$this->collExams = array();
	}

	/**
	 * Gets an array of Exam objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related Exams from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Exam[]
	 * @throws     PropelException
	 */
	public function getExams($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collExams === null) {
			if ($this->isNew()) {
			   $this->collExams = array();
			} else {

				$criteria->add(ExamPeer::TYPE, $this->id);

				ExamPeer::addSelectColumns($criteria);
				$this->collExams = ExamPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ExamPeer::TYPE, $this->id);

				ExamPeer::addSelectColumns($criteria);
				if (!isset($this->lastExamCriteria) || !$this->lastExamCriteria->equals($criteria)) {
					$this->collExams = ExamPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastExamCriteria = $criteria;
		return $this->collExams;
	}

	/**
	 * Returns the number of related Exam objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Exam objects.
	 * @throws     PropelException
	 */
	public function countExams(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collExams === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ExamPeer::TYPE, $this->id);

				$count = ExamPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ExamPeer::TYPE, $this->id);

				if (!isset($this->lastExamCriteria) || !$this->lastExamCriteria->equals($criteria)) {
					$count = ExamPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collExams);
				}
			} else {
				$count = count($this->collExams);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Exam object to this object
	 * through the Exam foreign key attribute.
	 *
	 * @param      Exam $l Exam
	 * @return     void
	 * @throws     PropelException
	 */
	public function addExam(Exam $l)
	{
		if ($this->collExams === null) {
			$this->initExams();
		}
		if (!in_array($l, $this->collExams, true)) { // only add it if the **same** object is not already associated
			array_push($this->collExams, $l);
			$l->setEnumItem($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EnumItem is new, it will return
	 * an empty collection; or if this EnumItem has previously
	 * been saved, it will retrieve related Exams from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EnumItem.
	 */
	public function getExamsJoinCourse($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collExams === null) {
			if ($this->isNew()) {
				$this->collExams = array();
			} else {

				$criteria->add(ExamPeer::TYPE, $this->id);

				$this->collExams = ExamPeer::doSelectJoinCourse($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ExamPeer::TYPE, $this->id);

			if (!isset($this->lastExamCriteria) || !$this->lastExamCriteria->equals($criteria)) {
				$this->collExams = ExamPeer::doSelectJoinCourse($criteria, $con, $join_behavior);
			}
		}
		$this->lastExamCriteria = $criteria;

		return $this->collExams;
	}

	/**
	 * Clears out the collImportMappingsRelatedByImportFileType collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addImportMappingsRelatedByImportFileType()
	 */
	public function clearImportMappingsRelatedByImportFileType()
	{
		$this->collImportMappingsRelatedByImportFileType = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collImportMappingsRelatedByImportFileType collection (array).
	 *
	 * By default this just sets the collImportMappingsRelatedByImportFileType collection to an empty array (like clearcollImportMappingsRelatedByImportFileType());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initImportMappingsRelatedByImportFileType()
	{
		$this->collImportMappingsRelatedByImportFileType = array();
	}

	/**
	 * Gets an array of ImportMapping objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related ImportMappingsRelatedByImportFileType from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ImportMapping[]
	 * @throws     PropelException
	 */
	public function getImportMappingsRelatedByImportFileType($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collImportMappingsRelatedByImportFileType === null) {
			if ($this->isNew()) {
			   $this->collImportMappingsRelatedByImportFileType = array();
			} else {

				$criteria->add(ImportMappingPeer::IMPORT_FILE_TYPE, $this->id);

				ImportMappingPeer::addSelectColumns($criteria);
				$this->collImportMappingsRelatedByImportFileType = ImportMappingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ImportMappingPeer::IMPORT_FILE_TYPE, $this->id);

				ImportMappingPeer::addSelectColumns($criteria);
				if (!isset($this->lastImportMappingRelatedByImportFileTypeCriteria) || !$this->lastImportMappingRelatedByImportFileTypeCriteria->equals($criteria)) {
					$this->collImportMappingsRelatedByImportFileType = ImportMappingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastImportMappingRelatedByImportFileTypeCriteria = $criteria;
		return $this->collImportMappingsRelatedByImportFileType;
	}

	/**
	 * Returns the number of related ImportMapping objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ImportMapping objects.
	 * @throws     PropelException
	 */
	public function countImportMappingsRelatedByImportFileType(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collImportMappingsRelatedByImportFileType === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ImportMappingPeer::IMPORT_FILE_TYPE, $this->id);

				$count = ImportMappingPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ImportMappingPeer::IMPORT_FILE_TYPE, $this->id);

				if (!isset($this->lastImportMappingRelatedByImportFileTypeCriteria) || !$this->lastImportMappingRelatedByImportFileTypeCriteria->equals($criteria)) {
					$count = ImportMappingPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collImportMappingsRelatedByImportFileType);
				}
			} else {
				$count = count($this->collImportMappingsRelatedByImportFileType);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ImportMapping object to this object
	 * through the ImportMapping foreign key attribute.
	 *
	 * @param      ImportMapping $l ImportMapping
	 * @return     void
	 * @throws     PropelException
	 */
	public function addImportMappingRelatedByImportFileType(ImportMapping $l)
	{
		if ($this->collImportMappingsRelatedByImportFileType === null) {
			$this->initImportMappingsRelatedByImportFileType();
		}
		if (!in_array($l, $this->collImportMappingsRelatedByImportFileType, true)) { // only add it if the **same** object is not already associated
			array_push($this->collImportMappingsRelatedByImportFileType, $l);
			$l->setEnumItemRelatedByImportFileType($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EnumItem is new, it will return
	 * an empty collection; or if this EnumItem has previously
	 * been saved, it will retrieve related ImportMappingsRelatedByImportFileType from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EnumItem.
	 */
	public function getImportMappingsRelatedByImportFileTypeJoinRatingField($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collImportMappingsRelatedByImportFileType === null) {
			if ($this->isNew()) {
				$this->collImportMappingsRelatedByImportFileType = array();
			} else {

				$criteria->add(ImportMappingPeer::IMPORT_FILE_TYPE, $this->id);

				$this->collImportMappingsRelatedByImportFileType = ImportMappingPeer::doSelectJoinRatingField($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ImportMappingPeer::IMPORT_FILE_TYPE, $this->id);

			if (!isset($this->lastImportMappingRelatedByImportFileTypeCriteria) || !$this->lastImportMappingRelatedByImportFileTypeCriteria->equals($criteria)) {
				$this->collImportMappingsRelatedByImportFileType = ImportMappingPeer::doSelectJoinRatingField($criteria, $con, $join_behavior);
			}
		}
		$this->lastImportMappingRelatedByImportFileTypeCriteria = $criteria;

		return $this->collImportMappingsRelatedByImportFileType;
	}

	/**
	 * Clears out the collImportMappingsRelatedByMapping collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addImportMappingsRelatedByMapping()
	 */
	public function clearImportMappingsRelatedByMapping()
	{
		$this->collImportMappingsRelatedByMapping = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collImportMappingsRelatedByMapping collection (array).
	 *
	 * By default this just sets the collImportMappingsRelatedByMapping collection to an empty array (like clearcollImportMappingsRelatedByMapping());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initImportMappingsRelatedByMapping()
	{
		$this->collImportMappingsRelatedByMapping = array();
	}

	/**
	 * Gets an array of ImportMapping objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related ImportMappingsRelatedByMapping from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ImportMapping[]
	 * @throws     PropelException
	 */
	public function getImportMappingsRelatedByMapping($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collImportMappingsRelatedByMapping === null) {
			if ($this->isNew()) {
			   $this->collImportMappingsRelatedByMapping = array();
			} else {

				$criteria->add(ImportMappingPeer::MAPPING, $this->id);

				ImportMappingPeer::addSelectColumns($criteria);
				$this->collImportMappingsRelatedByMapping = ImportMappingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ImportMappingPeer::MAPPING, $this->id);

				ImportMappingPeer::addSelectColumns($criteria);
				if (!isset($this->lastImportMappingRelatedByMappingCriteria) || !$this->lastImportMappingRelatedByMappingCriteria->equals($criteria)) {
					$this->collImportMappingsRelatedByMapping = ImportMappingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastImportMappingRelatedByMappingCriteria = $criteria;
		return $this->collImportMappingsRelatedByMapping;
	}

	/**
	 * Returns the number of related ImportMapping objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ImportMapping objects.
	 * @throws     PropelException
	 */
	public function countImportMappingsRelatedByMapping(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collImportMappingsRelatedByMapping === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ImportMappingPeer::MAPPING, $this->id);

				$count = ImportMappingPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ImportMappingPeer::MAPPING, $this->id);

				if (!isset($this->lastImportMappingRelatedByMappingCriteria) || !$this->lastImportMappingRelatedByMappingCriteria->equals($criteria)) {
					$count = ImportMappingPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collImportMappingsRelatedByMapping);
				}
			} else {
				$count = count($this->collImportMappingsRelatedByMapping);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ImportMapping object to this object
	 * through the ImportMapping foreign key attribute.
	 *
	 * @param      ImportMapping $l ImportMapping
	 * @return     void
	 * @throws     PropelException
	 */
	public function addImportMappingRelatedByMapping(ImportMapping $l)
	{
		if ($this->collImportMappingsRelatedByMapping === null) {
			$this->initImportMappingsRelatedByMapping();
		}
		if (!in_array($l, $this->collImportMappingsRelatedByMapping, true)) { // only add it if the **same** object is not already associated
			array_push($this->collImportMappingsRelatedByMapping, $l);
			$l->setEnumItemRelatedByMapping($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this EnumItem is new, it will return
	 * an empty collection; or if this EnumItem has previously
	 * been saved, it will retrieve related ImportMappingsRelatedByMapping from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in EnumItem.
	 */
	public function getImportMappingsRelatedByMappingJoinRatingField($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collImportMappingsRelatedByMapping === null) {
			if ($this->isNew()) {
				$this->collImportMappingsRelatedByMapping = array();
			} else {

				$criteria->add(ImportMappingPeer::MAPPING, $this->id);

				$this->collImportMappingsRelatedByMapping = ImportMappingPeer::doSelectJoinRatingField($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ImportMappingPeer::MAPPING, $this->id);

			if (!isset($this->lastImportMappingRelatedByMappingCriteria) || !$this->lastImportMappingRelatedByMappingCriteria->equals($criteria)) {
				$this->collImportMappingsRelatedByMapping = ImportMappingPeer::doSelectJoinRatingField($criteria, $con, $join_behavior);
			}
		}
		$this->lastImportMappingRelatedByMappingCriteria = $criteria;

		return $this->collImportMappingsRelatedByMapping;
	}

	/**
	 * Clears out the collRatingFields collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRatingFields()
	 */
	public function clearRatingFields()
	{
		$this->collRatingFields = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRatingFields collection (array).
	 *
	 * By default this just sets the collRatingFields collection to an empty array (like clearcollRatingFields());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRatingFields()
	{
		$this->collRatingFields = array();
	}

	/**
	 * Gets an array of RatingField objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related RatingFields from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RatingField[]
	 * @throws     PropelException
	 */
	public function getRatingFields($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRatingFields === null) {
			if ($this->isNew()) {
			   $this->collRatingFields = array();
			} else {

				$criteria->add(RatingFieldPeer::TYPE_ID, $this->id);

				RatingFieldPeer::addSelectColumns($criteria);
				$this->collRatingFields = RatingFieldPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RatingFieldPeer::TYPE_ID, $this->id);

				RatingFieldPeer::addSelectColumns($criteria);
				if (!isset($this->lastRatingFieldCriteria) || !$this->lastRatingFieldCriteria->equals($criteria)) {
					$this->collRatingFields = RatingFieldPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRatingFieldCriteria = $criteria;
		return $this->collRatingFields;
	}

	/**
	 * Returns the number of related RatingField objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RatingField objects.
	 * @throws     PropelException
	 */
	public function countRatingFields(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRatingFields === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RatingFieldPeer::TYPE_ID, $this->id);

				$count = RatingFieldPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RatingFieldPeer::TYPE_ID, $this->id);

				if (!isset($this->lastRatingFieldCriteria) || !$this->lastRatingFieldCriteria->equals($criteria)) {
					$count = RatingFieldPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRatingFields);
				}
			} else {
				$count = count($this->collRatingFields);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a RatingField object to this object
	 * through the RatingField foreign key attribute.
	 *
	 * @param      RatingField $l RatingField
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRatingField(RatingField $l)
	{
		if ($this->collRatingFields === null) {
			$this->initRatingFields();
		}
		if (!in_array($l, $this->collRatingFields, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRatingFields, $l);
			$l->setEnumItem($this);
		}
	}

	/**
	 * Clears out the collUsers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsers()
	 */
	public function clearUsers()
	{
		$this->collUsers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsers collection (array).
	 *
	 * By default this just sets the collUsers collection to an empty array (like clearcollUsers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsers()
	{
		$this->collUsers = array();
	}

	/**
	 * Gets an array of User objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this EnumItem has previously been saved, it will retrieve
	 * related Users from storage. If this EnumItem is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array User[]
	 * @throws     PropelException
	 */
	public function getUsers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsers === null) {
			if ($this->isNew()) {
			   $this->collUsers = array();
			} else {

				$criteria->add(UserPeer::TYPE_ID, $this->id);

				UserPeer::addSelectColumns($criteria);
				$this->collUsers = UserPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserPeer::TYPE_ID, $this->id);

				UserPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserCriteria) || !$this->lastUserCriteria->equals($criteria)) {
					$this->collUsers = UserPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserCriteria = $criteria;
		return $this->collUsers;
	}

	/**
	 * Returns the number of related User objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related User objects.
	 * @throws     PropelException
	 */
	public function countUsers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EnumItemPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserPeer::TYPE_ID, $this->id);

				$count = UserPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserPeer::TYPE_ID, $this->id);

				if (!isset($this->lastUserCriteria) || !$this->lastUserCriteria->equals($criteria)) {
					$count = UserPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUsers);
				}
			} else {
				$count = count($this->collUsers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a User object to this object
	 * through the User foreign key attribute.
	 *
	 * @param      User $l User
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUser(User $l)
	{
		if ($this->collUsers === null) {
			$this->initUsers();
		}
		if (!in_array($l, $this->collUsers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsers, $l);
			$l->setEnumItem($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCourseDisciplineAssociations) {
				foreach ((array) $this->collCourseDisciplineAssociations as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collEnumItemsRelatedByParentId) {
				foreach ((array) $this->collEnumItemsRelatedByParentId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collExams) {
				foreach ((array) $this->collExams as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collImportMappingsRelatedByImportFileType) {
				foreach ((array) $this->collImportMappingsRelatedByImportFileType as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collImportMappingsRelatedByMapping) {
				foreach ((array) $this->collImportMappingsRelatedByMapping as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRatingFields) {
				foreach ((array) $this->collRatingFields as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUsers) {
				foreach ((array) $this->collUsers as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCourseDisciplineAssociations = null;
		$this->collEnumItemsRelatedByParentId = null;
		$this->collExams = null;
		$this->collImportMappingsRelatedByImportFileType = null;
		$this->collImportMappingsRelatedByMapping = null;
		$this->collRatingFields = null;
		$this->collUsers = null;
			$this->aEnumItemRelatedByParentId = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEnumItem:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEnumItem::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEnumItem
