<?php

/**
 * Base class that represents a row from the 'auto_course_rating_data' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 07/17/09 09:48:44
 *
 * @package    lib.model.om
 */
abstract class BaseAutoCourseRating extends BaseObject  implements Persistent {


  const PEER = 'AutoCourseRatingPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AutoCourseRatingPeer
	 */
	protected static $peer;

	/**
	 * The value for the field_id field.
	 * @var        int
	 */
	protected $field_id;

	/**
	 * The value for the rating field.
	 * @var        int
	 */
	protected $rating;

	/**
	 * The value for the import_dt field.
	 * @var        string
	 */
	protected $import_dt;

	/**
	 * The value for the course_id field.
	 * @var        string
	 */
	protected $course_id;

	/**
	 * The value for the number field.
	 * @var        int
	 */
	protected $number;

	/**
	 * @var        RatingField
	 */
	protected $aRatingField;

	/**
	 * @var        Course
	 */
	protected $aCourse;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseAutoCourseRating object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [field_id] column value.
	 * 
	 * @return     int
	 */
	public function getFieldId()
	{
		return $this->field_id;
	}

	/**
	 * Get the [rating] column value.
	 * 
	 * @return     int
	 */
	public function getRating()
	{
		return $this->rating;
	}

	/**
	 * Get the [optionally formatted] temporal [import_dt] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getImportDt($format = 'Y-m-d H:i:s')
	{
		if ($this->import_dt === null) {
			return null;
		}


		if ($this->import_dt === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->import_dt);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->import_dt, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [course_id] column value.
	 * 
	 * @return     string
	 */
	public function getCourseId()
	{
		return $this->course_id;
	}

	/**
	 * Get the [number] column value.
	 * 
	 * @return     int
	 */
	public function getNumber()
	{
		return $this->number;
	}

	/**
	 * Set the value of [field_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AutoCourseRating The current object (for fluent API support)
	 */
	public function setFieldId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->field_id !== $v) {
			$this->field_id = $v;
			$this->modifiedColumns[] = AutoCourseRatingPeer::FIELD_ID;
		}

		if ($this->aRatingField !== null && $this->aRatingField->getId() !== $v) {
			$this->aRatingField = null;
		}

		return $this;
	} // setFieldId()

	/**
	 * Set the value of [rating] column.
	 * 
	 * @param      int $v new value
	 * @return     AutoCourseRating The current object (for fluent API support)
	 */
	public function setRating($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rating !== $v) {
			$this->rating = $v;
			$this->modifiedColumns[] = AutoCourseRatingPeer::RATING;
		}

		return $this;
	} // setRating()

	/**
	 * Sets the value of [import_dt] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AutoCourseRating The current object (for fluent API support)
	 */
	public function setImportDt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->import_dt !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->import_dt !== null && $tmpDt = new DateTime($this->import_dt)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->import_dt = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AutoCourseRatingPeer::IMPORT_DT;
			}
		} // if either are not null

		return $this;
	} // setImportDt()

	/**
	 * Set the value of [course_id] column.
	 * 
	 * @param      string $v new value
	 * @return     AutoCourseRating The current object (for fluent API support)
	 */
	public function setCourseId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->course_id !== $v) {
			$this->course_id = $v;
			$this->modifiedColumns[] = AutoCourseRatingPeer::COURSE_ID;
		}

		if ($this->aCourse !== null && $this->aCourse->getId() !== $v) {
			$this->aCourse = null;
		}

		return $this;
	} // setCourseId()

	/**
	 * Set the value of [number] column.
	 * 
	 * @param      int $v new value
	 * @return     AutoCourseRating The current object (for fluent API support)
	 */
	public function setNumber($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->number !== $v) {
			$this->number = $v;
			$this->modifiedColumns[] = AutoCourseRatingPeer::NUMBER;
		}

		return $this;
	} // setNumber()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->field_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->rating = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->import_dt = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->course_id = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->number = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = AutoCourseRatingPeer::NUM_COLUMNS - AutoCourseRatingPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AutoCourseRating object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aRatingField !== null && $this->field_id !== $this->aRatingField->getId()) {
			$this->aRatingField = null;
		}
		if ($this->aCourse !== null && $this->course_id !== $this->aCourse->getId()) {
			$this->aCourse = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AutoCourseRatingPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AutoCourseRatingPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aRatingField = null;
			$this->aCourse = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAutoCourseRating:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AutoCourseRatingPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AutoCourseRatingPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAutoCourseRating:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAutoCourseRating:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AutoCourseRatingPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAutoCourseRating:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AutoCourseRatingPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRatingField !== null) {
				if ($this->aRatingField->isModified() || $this->aRatingField->isNew()) {
					$affectedRows += $this->aRatingField->save($con);
				}
				$this->setRatingField($this->aRatingField);
			}

			if ($this->aCourse !== null) {
				if ($this->aCourse->isModified() || $this->aCourse->isNew()) {
					$affectedRows += $this->aCourse->save($con);
				}
				$this->setCourse($this->aCourse);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AutoCourseRatingPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += AutoCourseRatingPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRatingField !== null) {
				if (!$this->aRatingField->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRatingField->getValidationFailures());
				}
			}

			if ($this->aCourse !== null) {
				if (!$this->aCourse->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCourse->getValidationFailures());
				}
			}


			if (($retval = AutoCourseRatingPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AutoCourseRatingPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getFieldId();
				break;
			case 1:
				return $this->getRating();
				break;
			case 2:
				return $this->getImportDt();
				break;
			case 3:
				return $this->getCourseId();
				break;
			case 4:
				return $this->getNumber();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AutoCourseRatingPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getFieldId(),
			$keys[1] => $this->getRating(),
			$keys[2] => $this->getImportDt(),
			$keys[3] => $this->getCourseId(),
			$keys[4] => $this->getNumber(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AutoCourseRatingPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setFieldId($value);
				break;
			case 1:
				$this->setRating($value);
				break;
			case 2:
				$this->setImportDt($value);
				break;
			case 3:
				$this->setCourseId($value);
				break;
			case 4:
				$this->setNumber($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AutoCourseRatingPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setFieldId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRating($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setImportDt($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCourseId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setNumber($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AutoCourseRatingPeer::DATABASE_NAME);

		if ($this->isColumnModified(AutoCourseRatingPeer::FIELD_ID)) $criteria->add(AutoCourseRatingPeer::FIELD_ID, $this->field_id);
		if ($this->isColumnModified(AutoCourseRatingPeer::RATING)) $criteria->add(AutoCourseRatingPeer::RATING, $this->rating);
		if ($this->isColumnModified(AutoCourseRatingPeer::IMPORT_DT)) $criteria->add(AutoCourseRatingPeer::IMPORT_DT, $this->import_dt);
		if ($this->isColumnModified(AutoCourseRatingPeer::COURSE_ID)) $criteria->add(AutoCourseRatingPeer::COURSE_ID, $this->course_id);
		if ($this->isColumnModified(AutoCourseRatingPeer::NUMBER)) $criteria->add(AutoCourseRatingPeer::NUMBER, $this->number);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AutoCourseRatingPeer::DATABASE_NAME);

		$criteria->add(AutoCourseRatingPeer::FIELD_ID, $this->field_id);
		$criteria->add(AutoCourseRatingPeer::RATING, $this->rating);
		$criteria->add(AutoCourseRatingPeer::IMPORT_DT, $this->import_dt);
		$criteria->add(AutoCourseRatingPeer::COURSE_ID, $this->course_id);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getFieldId();

		$pks[1] = $this->getRating();

		$pks[2] = $this->getImportDt();

		$pks[3] = $this->getCourseId();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setFieldId($keys[0]);

		$this->setRating($keys[1]);

		$this->setImportDt($keys[2]);

		$this->setCourseId($keys[3]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AutoCourseRating (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFieldId($this->field_id);

		$copyObj->setRating($this->rating);

		$copyObj->setImportDt($this->import_dt);

		$copyObj->setCourseId($this->course_id);

		$copyObj->setNumber($this->number);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AutoCourseRating Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AutoCourseRatingPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AutoCourseRatingPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a RatingField object.
	 *
	 * @param      RatingField $v
	 * @return     AutoCourseRating The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRatingField(RatingField $v = null)
	{
		if ($v === null) {
			$this->setFieldId(NULL);
		} else {
			$this->setFieldId($v->getId());
		}

		$this->aRatingField = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RatingField object, it will not be re-added.
		if ($v !== null) {
			$v->addAutoCourseRating($this);
		}

		return $this;
	}


	/**
	 * Get the associated RatingField object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RatingField The associated RatingField object.
	 * @throws     PropelException
	 */
	public function getRatingField(PropelPDO $con = null)
	{
		if ($this->aRatingField === null && ($this->field_id !== null)) {
			$c = new Criteria(RatingFieldPeer::DATABASE_NAME);
			$c->add(RatingFieldPeer::ID, $this->field_id);
			$this->aRatingField = RatingFieldPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRatingField->addAutoCourseRatings($this);
			 */
		}
		return $this->aRatingField;
	}

	/**
	 * Declares an association between this object and a Course object.
	 *
	 * @param      Course $v
	 * @return     AutoCourseRating The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCourse(Course $v = null)
	{
		if ($v === null) {
			$this->setCourseId(NULL);
		} else {
			$this->setCourseId($v->getId());
		}

		$this->aCourse = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Course object, it will not be re-added.
		if ($v !== null) {
			$v->addAutoCourseRating($this);
		}

		return $this;
	}


	/**
	 * Get the associated Course object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Course The associated Course object.
	 * @throws     PropelException
	 */
	public function getCourse(PropelPDO $con = null)
	{
		if ($this->aCourse === null && (($this->course_id !== "" && $this->course_id !== null))) {
			$c = new Criteria(CoursePeer::DATABASE_NAME);
			$c->add(CoursePeer::ID, $this->course_id);
			$this->aCourse = CoursePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCourse->addAutoCourseRatings($this);
			 */
		}
		return $this->aCourse;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aRatingField = null;
			$this->aCourse = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAutoCourseRating:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAutoCourseRating::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAutoCourseRating
