<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/10/17 21:59:05

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=webdev_staging;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'phptype' => 'mysql',
  'hostspec' => 'localhost',
  'database' => 'webdev_staging',
  'name' => 'propel',
)),);
