<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/10/31 01:19:54
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
