<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/11/09 23:01:01
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
