dev:
  propel:
    param:
      classname:  DebugPDO
      hostspec:   localhost
      username:   root
      password:   root
      database:   skulecourses
      phptype:    mysql

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=skulecourses;host=localhost
      username:   root
      password:   root
      encoding:   utf8
      persistent: true
      pooling:    true
      phptype:    mysql
