dev:
  propel:
    param:
      classname:  DebugPDO
      hostspec:   localhost
      username:   root
      password:   
      database:   webdev_staging
      phptype:    mysql

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=webdev_staging;host=localhost
      username:   root
      password:   
      encoding:   utf8
      persistent: true
      pooling:    true
      phptype:    mysql
